### ISSUE TITLE
AProf exception in AProfOps.allocateSize

### ISSUE THREAD

**Issue by krilak** [Devexperts/aprof#5]
We received the following error in our logs after enabling aprof. We are using jdk 1.8.0_112:

`2017-04-19T09:17:57.943-0500: aprof: #1552 Failed to process: com.devexperts.tos.qdext.volatility.VolatilityContainer [in sun.misc.Launcher$AppClassLoader@414493378] with error 

java.lang.RuntimeException
2017-04-19T09:17:57.943-0500: aprof: java.lang.RuntimeException
  14419 1475       3       java.lang.StringBuilder::charAt (6 bytes)
  14419 1476       3       java.lang.AbstractStringBuilder::charAt (49 bytes)
2017-04-19T09:17:57.943-0500: aprof:    at org.objectweb.asm.MethodVisitor.visitTypeAnnotation(Unknown Source)
2017-04-19T09:17:57.943-0500: aprof:    at org.objectweb.asm.ClassReader.b(Unknown Source)
2017-04-19T09:17:57.943-0500: aprof:    at org.objectweb.asm.ClassReader.accept(Unknown Source)
2017-04-19T09:17:57.943-0500: aprof:    at org.objectweb.asm.ClassReader.accept(Unknown Source)
2017-04-19T09:17:57.943-0500: aprof:    at com.devexperts.aprof.transformer.AProfTransformer.transformImpl(AProfTransformer.java:103)
2017-04-19T09:17:57.943-0500: aprof:    at com.devexperts.aprof.transformer.AProfTransformer.transform(AProfTransformer.java:64)
2017-04-19T09:17:57.943-0500: aprof:    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
2017-04-19T09:17:57.943-0500: aprof:    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
2017-04-19T09:17:57.943-0500: aprof:    at java.lang.ClassLoader.defineClass1(Native Method)
2017-04-19T09:17:57.943-0500: aprof:    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
2017-04-19T09:17:57.943-0500: aprof:    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2017-04-19T09:17:57.943-0500: aprof:    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2017-04-19T09:17:57.943-0500: aprof:    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2017-04-19T09:17:57.944-0500: aprof:    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2017-04-19T09:17:57.944-0500: aprof:    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2017-04-19T09:17:57.944-0500: aprof:    at java.security.AccessController.doPrivileged(Native Method)
2017-04-19T09:17:57.944-0500: aprof:    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2017-04-19T09:17:57.944-0500: aprof:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2017-04-19T09:17:57.944-0500: aprof:    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2017-04-19T09:17:57.944-0500: aprof:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2017-04-19T09:17:57.944-0500: aprof:    at com.devexperts.tos.qdext.volatility.VolatilityObjField.<clinit>(VolatilityObjField.java:39)
2017-04-19T09:17:57.944-0500: aprof:    at sun.misc.Unsafe.allocateInstance(Native Method)
2017-04-19T09:17:57.944-0500: aprof:    at com.devexperts.aprof.AProfSizeUtil.getObjectSizeByClass(AProfSizeUtil.java:102)
2017-04-19T09:17:57.944-0500: aprof:    at com.devexperts.aprof.AProfOps.allocateSize(AProfOps.java:41)
`
This seems to be related to the following line in VolatilityObjField: 
private static final String ILLEGAL_VALUE_MSG_TEMPLATE = "Illegal value: %s, must be " +
			VolatilityContainer.class.getName();

**Comment by tsitelov** [comment]
should be fixed with current changes in master
