### ISSUE TITLE
 AProf failed to process simple enum class

### ISSUE THREAD

**Issue by krilak** [Devexperts/aprof#6]
We see this error in our logs, where it fails for a simple enum class. 

2017-03-20T11:39:03.949-0500: aprof: #1932 Failed to process: com.devexperts.logging.LogLevel [in sun.misc.Launcher$AppClassLoader@414493378] with error 

java.lang.RuntimeException
[Loaded java.lang.Throwable$PrintStreamOrWriter from /opt/java/jdk1.8.0_112/jre/lib/rt.jar]
[Loaded java.lang.Throwable$WrappedPrintWriter from /opt/java/jdk1.8.0_112/jre/lib/rt.jar]
[Loaded java.util.IdentityHashMap$KeySet from /opt/java/jdk1.8.0_112/jre/lib/rt.jar]
2017-03-20T11:39:03.956-0500: aprof: java.lang.RuntimeException
2017-03-20T11:39:03.962-0500: aprof:    at org.objectweb.asm.MethodVisitor.visitTypeAnnotation(Unknown Source)
  73201 1216  s    2       java.io.BufferedOutputStream::flush (12 bytes)
  73202 1217       2       java.io.OutputStream::flush (1 bytes)
2017-03-20T11:39:03.962-0500: aprof:    at org.objectweb.asm.ClassReader.b(Unknown Source)
  73202 1218   !   2       com.devexperts.aprof.util.FastFmtUtil::print2 (146 bytes)
2017-03-20T11:39:03.963-0500: aprof:    at org.objectweb.asm.ClassReader.accept(Unknown Source)
2017-03-20T11:39:03.964-0500: aprof:    at org.objectweb.asm.ClassReader.accept(Unknown Source)
2017-03-20T11:39:03.964-0500: aprof:    at com.devexperts.aprof.transformer.AProfTransformer.transformImpl(AProfTransformer.java:103)
2017-03-20T11:39:03.964-0500: aprof:    at com.devexperts.aprof.transformer.AProfTransformer.transform(AProfTransformer.java:64)
2017-03-20T11:39:03.964-0500: aprof:    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
2017-03-20T11:39:03.964-0500: aprof:    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
2017-03-20T11:39:03.964-0500: aprof:    at java.lang.ClassLoader.defineClass1(Native Method)
2017-03-20T11:39:03.965-0500: aprof:    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  73204 1219   !   2       java.io.PrintWriter::println (27 bytes)
[LogLevel.zip](https://github.com/Devexperts/aprof/files/935358/LogLevel.zip)

  73205 1220   !   2       java.io.PrintWriter::newLine (66 bytes)
2017-03-20T11:39:03.965-0500: aprof:    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
2017-03-20T11:39:03.970-0500: aprof:    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
2017-03-20T11:39:03.970-0500: aprof:    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
2017-03-20T11:39:03.970-0500: aprof:    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
2017-03-20T11:39:03.970-0500: aprof:    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
2017-03-20T11:39:03.970-0500: aprof:    at java.security.AccessController.doPrivileged(Native Method)
2017-03-20T11:39:03.970-0500: aprof:    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
2017-03-20T11:39:03.970-0500: aprof:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2017-03-20T11:39:03.970-0500: aprof:    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
2017-03-20T11:39:03.970-0500: aprof:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2017-03-20T11:39:03.970-0500: aprof:    at com.devexperts.logging.LoggingGroup.<init>(LoggingGroup.java:18)
2017-03-20T11:39:03.971-0500: aprof:    at com.devexperts.logging.LoggingGroup.<clinit>(LoggingGroup.java:10)
2017-03-20T11:39:03.971-0500: aprof:    at com.devexperts.logging.DynamicLogging.getLogger(DynamicLogging.java:39)
2017-03-20T11:39:03.971-0500: aprof:    at com.devexperts.tos.backend.scriptcalculator.ScriptCalculator.<clinit>(ScriptCalculator.java:71)

**Comment by tsitelov** [comment]
should be fixed with current changes in master
